<form id="admin-grid-form" action="<?php echo $this->getGridUrl()?>" method="post">  
<div class="content-header">
    <table cellspacing="0">
        <tbody>
            <tr>
                <td style="width: 50%;">
                    <h3 class="icon-head head-adminhtml-admin">
                        <?php echo $this->translate('Manage Admins');?>
                    </h3>
                </td>
                <td class="form-buttons">
                    <button onclick="admin.setElement('main-container').setUseType('url').setURL('<?php echo $this->getCreateUrl() ?>').loadPage();" type="button" title="<?php echo $this->translate('Create Admin');?>" class="scalable add">
                        <span><span><span>
                        <?php echo $this->translate('Create Admin');?>
                        </span></span></span>
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div id="grid-list"></div>
</form>
<script>
var admin = new Ccc.Admin();
admin.setObject('admin');
admin.resetCheckedElements();
admin.setForm('admin-grid-form');
admin.setUseType('url');
admin.setURL('<?php echo $this->getGridUrl()?>');
if(admin.getForm())
{
    admin.loadPage();
}
</script>