<?php 
$object = $this->getObject();
?>
<div class="columns" style="background: none;">
    <div class="side-col" id="page:left" style="display: none;">
        <h3><?php echo $this->translate('Manage Footer'); ?></h3>
        
        <ul id="page_tabs" class="tabs">
            <li>
                <a href="javascript:void(0);" class="tabHeader tab-item-link" name="main_section" title="System Config" id="html">
                    <span>Footer Settings</span>
                </a>
            </li>
        </ul>
    </div>
    <!-- TABS START -->
    <div id="content">
        <div class="main-col-inner">
                <div id="messages"></div>
                       
                <div class="entry-edit">
                    <form id="config_frm" action="<?php echo $this->getSaveUrl(); ?>" method="post" enctype="multipart/form-data"> 
                        <div class="tabContent" style="display: none;">
                            <div class="entry-edit">
                                <div class="entry-edit-head">
                                    <h4 class="icon-head head-edit-form fieldset-legend">Footer Settings</h4>
                                    <div class="form-buttons"></div>
                                </div>
                                <div class="fieldset " id="page_base_fieldset">
                                    <div class="hor-scroll">
                                        <table class="form-list" cellspacing="0">
                                            <tbody>
                                                <tr>
                                                    <td class="label">
                                                        <label for="page_title">
                                                            <?php echo $this->translate('Footer One Title'); ?>
                                                        </label>
                                                    </td>
                                                    <td class="value">
                                                        <?php echo $this->FormText('config[footer_one_title]',$this->getFooterOneTitleConfig()->value, array('class'=>'input-text', 'maxlength'=>255)) ;?>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="label">
                                                        <label for="page_title">
                                                            <?php echo $this->translate('Footer One Description'); ?>
                                                        </label>
                                                    </td>
                                                    <td class="value" style="width: 100%;">
                                                        <?php echo $this->FormTextarea('config[footer_one_description]', $this->getFooterOneDescriptionConfig()->value, array('id'=>'config-footer_one_description', 'class'=>'input-text editor', "style"=>"width:100%;")) ;?>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="label">
                                                        <label for="page_title">
                                                            <?php echo $this->translate('Footer Two Title'); ?>
                                                        </label>
                                                    </td>
                                                    <td class="value">
                                                        <?php echo $this->FormText('config[footer_two_title]',$this->getFooterTwoTitleConfig()->value, array('class'=>'input-text', 'maxlength'=>255)) ;?>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="label">
                                                        <label for="page_title">
                                                            <?php echo $this->translate('Footer Two Description'); ?>
                                                        </label>
                                                    </td>
                                                    <td class="value" style="width: 100%;">
                                                        <?php echo $this->FormTextarea('config[footer_two_description]', $this->getFooterTwoDescriptionConfig()->value, array('id'=>'config-footer_two_description', 'class'=>'input-text editor', "style"=>"width:100%;")) ;?>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="label">
                                                        <label for="page_title">
                                                            <?php echo $this->translate('Footer Three Title'); ?>
                                                        </label>
                                                    </td>
                                                    <td class="value">
                                                        <?php echo $this->FormText('config[footer_three_title]',$this->getFooterThreeTitleConfig()->value, array('class'=>'input-text', 'maxlength'=>255)) ;?>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td class="label">
                                                        <label for="page_title">
                                                            <?php echo $this->translate('Footer Three Description'); ?>
                                                        </label>
                                                    </td>
                                                    <td class="value" style="width: 100%;">
                                                        <?php echo $this->FormTextarea('config[footer_three_description]', $this->getFooterThreeDescriptionConfig()->value, array('id'=>'config-footer_three_description', 'class'=>'input-text editor', "style"=>"width:100%;")) ;?>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
        </div>
    </div>
    <!-- TABS END -->
</div>

<script>
var tabObject = new Core.Tab();
jQuery(document).ready(function()
{
    tabObject.setupTab();
    
    jQuery("#config-footer_one_description").redactor({
            imageUpload: '<?php echo $this->url(array("module"=>"core", "controller"=>"index", "action"=>"upload-image")); ?>',
    });
    
    jQuery("#config-footer_two_description").redactor({
            imageUpload: '<?php echo $this->url(array("module"=>"core", "controller"=>"index", "action"=>"upload-image")); ?>',
    });
    
    jQuery("#config-footer_three_description").redactor({
            imageUpload: '<?php echo $this->url(array("module"=>"core", "controller"=>"index", "action"=>"upload-image")); ?>',
    });
});
</script>