<?php 
$tag = $this->getTag();    
$websites = $this->getCollection();   
$object = $this->getObject();
?>

<input type="hidden" name="selectedIds" id="selectedIds" value=""/>
<div>
    <div>
        <table class="actions" cellspacing="0">
            <tbody>
                <tr>
                    <td class="pager">
                        <?php if($websites): ?>
                            <?php echo $this->paginationControl($websites, 'Sliding', 'pages/html/pager.phtml'); ?>
                        <?php endif;?>
                    </td>
                    <td class="filter-actions a-right">
                        <button id="" title="Reset Filter" type="button" class="scalable " onclick="<?php echo $object; ?>.setFormURL('<?php echo $this->getResetUrl()?>').loadPage();">
                            <span><span><span><?php echo $this->translate('Reset Filter')?></span></span></span>
                        </button>
                        <button title="Search" type="submit" class="scalable" style="" onclick="<?php echo $object; ?>.setFormURL('<?php echo $this->getGridUrl()?>').loadPage(); return false;">
                            <span><span><span><?php echo $this->translate('Search')?></span></span></span>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
        
        <div id="periodGrid_massaction">
            <table class="massaction" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td>
                            <a href="javascript:void(0);" onclick="<?php echo $object; ?>.selectAll()">Select All</a>
                            <span class="separator">|</span>
                            <a href="javascript:void(0);" onclick="<?php echo $object; ?>.unselectAll()">Unselect All</a>
                            <span class="separator">|</span>
                            <a href="javascript:void(0);" onclick="<?php echo $object; ?>.selectVisible()">Select Visible</a>
                            <span class="separator">|</span>
                            <a href="javascript:void(0);" onclick="<?php echo $object; ?>.unselectVisible()">Unselect Visible</a>
                            <span class="separator">|</span>
                            <span id="row-count">0</span>
                             items selected
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        
        <div class="grid">
            <div class="hor-scroll">
                <table class="data" id="periodGrid_table" cellspacing="0">
                    <colgroup>
                        <col class="a-center" width="50">
                        <col width="100">
                        <col width="">
                        <col width="120">
                        <col width="150">
                        <col width="150">
                    </colgroup>
                    <thead>
                        <tr class="headings">
                            <th class="no-link">
                                <span class="nobr">&nbsp;</span>
                            </th>
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('ID'),'W.website_id') ?></span>
                            </th>
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('Name'),'W.name') ?></span>
                            </th>
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('Is Enabled'),'W.is_enabled') ?></span>
                            </th> 
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('Created On'),'W.created_date') ?></span>
                            </th>
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('Updated On'),'W.updated_date') ?></span>
                            </th>
                        </tr>
                        <tr class="filter">
                            <th></th>
                            <th>
                                <div class="field-100">
                                    <table width="160" cellpadding="0" cellspacing="0">
                                        <tr>
                                            <td valign="top"><?php echo $this->translate('From:')?></td>
                                            <td><?php echo $this->formText("website_id_from",$this->search()->website_id_from, array('class'=>'input-text', 'maxlength'=>11)); ?></td>
                                        </tr>
                                        <tr>
                                            <td valign="top"><?php echo $this->translate('To:')?></td>
                                            <td><?php echo $this->formText("website_id_to", $this->search()->website_id_to, array('class'=>'input-text', 'maxlength'=>11)); ?></td>
                                        </tr>
                                    </table>
                                </div>                                
                            </th>
                            <th>
                                <div class="field-100">
                                    <?php echo $this->formText("name", $this->search()->name, array('class'=>'input-text', 'maxlength'=>254)); ?>
                                </div>
                            </th>
                            <th>
                                <div>
                                    <?php echo $this->formSelect("is_enabled", $this->search()->is_enabled, array('class'=>'input-select'), $this->getIsEnabledOptions()); ?>
                                </div>
                            </th>
                            <th>
                                <div class="field-100">
                                    <table width="160" cellpadding="0" cellspacing="0">
                                        <tr>
                                            <td valign="top"><?php echo $this->translate('From:')?></td>
                                            <td><?php echo $this->formText("created_date_from", $this->search()->created_date_from, array('id'=>'created_from_date', 'class'=>'w2em format-y-m-d divider-dash input-text', 'readonly'=>'readonly', 'style'=>'width: 90px; align:center; vertical-align: middle;')); ?></td>
                                        </tr>
                                        <tr>
                                            <td valign="top"><?php echo $this->translate('To:')?></td>
                                            <td><?php echo $this->formText("created_date_to", $this->search()->created_date_to, array('id'=>'created_to_date', 'class'=>'w2em format-y-m-d divider-dash input-text', 'readonly'=>'readonly', 'style'=>'width: 90px; align:center; vertical-align: middle;')); ?></td>
                                        </tr>
                                    </table>
                                </div>
                            </th>
                            <th>
                                <div class="field-100">
                                    <table width="160" cellpadding="0" cellspacing="0">
                                        <tr>
                                            <td valign="top"><?php echo $this->translate('From:')?></td>
                                            <td><?php echo $this->formText("updated_date_from", $this->search()->updated_date_from, array('id'=>'updated_from_date', 'class'=>'w2em format-y-m-d divider-dash input-text', 'readonly'=>'readonly', 'style'=>'width: 90px; align:center; vertical-align: middle;')); ?></td>
                                        </tr>
                                        <tr>
                                            <td valign="top"><?php echo $this->translate('To:')?></td>
                                            <td><?php echo $this->formText("updated_date_to", $this->search()->updated_date_to, array('id'=>'updated_to_date', 'class'=>'w2em format-y-m-d divider-dash input-text', 'readonly'=>'readonly', 'style'=>'width: 90px; align:center; vertical-align: middle;')); ?></td>
                                        </tr>
                                    </table>
                                </div>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if(count($websites)): ?>
                            <?php $cnt = 0; ?>
                            <?php foreach($websites as $_website): ?>
                            <tr class="<?php if(($cnt+1)%2==0): ?>odd<?php else:?>even<?php endif; ?> pointer">
                                <td class="a-center ">
                                    <?php echo $this->formCheckbox("check_single[]", $_website->website_id, array('class'=>'check_single input-checkbox','id'=>'check_single checkbox-id-'.$_website->website_id,'onclick'=>"$object.checkSingle(this)")); ?>
                                </td>
                                <td class="a-right "><?php echo $this->escape($_website->website_id); ?></td>
                                <td class="a-left "><?php echo $this->escape($_website->name); ?></td>
                                <td class="a-left "><?php echo $this->getIsEnabled($_website); ?></td>   
                                <td class="a-center "><?php echo $this->date()->getFormattedDateView($_website->created_date); ?></td>
                                <td class="a-center "><?php echo $this->date()->getFormattedDateView($_website->updated_date); ?></td>
                            </tr>
                            <?php $cnt++; ?>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>
                                <td class="grid-column center no-record" colspan="14">
                                <?php echo $this->translate('Websites are not available.');?>
                                </td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                </table>            
            </div>
       </div>
    </div>
</div>

<script>
var elements = <?php echo json_encode($this->getAllIds()); ?>;
<?php echo $object; ?>.setAllElements(elements);
<?php if($tag->website_id): ?>
<?php echo $object; ?>.setCheckedElements(<?php echo $tag->website_id; ?>);
<?php endif; ?>
<?php echo $object; ?>.checkVisibleCheckbox(true);
<?php echo $object; ?>.printCheckedElementCount();
</script>

<script type="text/javascript">
jQuery('#created_from_date').datepicker({
    dateFormat : 'yy-mm-dd'
});

jQuery('#created_to_date').datepicker({
    dateFormat : 'yy-mm-dd'
});

jQuery('#updated_from_date').datepicker({
    dateFormat : 'yy-mm-dd'
});

jQuery('#updated_to_date').datepicker({
    dateFormat : 'yy-mm-dd'
});
</script>