<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title><?php echo $this->getTitle();?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('skin/admin/css/style.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('skin/admin/css/jquery.fancybox.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('skin/admin/css/ui-lightness/jquery-ui-1-10-0-custom.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('skin/admin/event/date_picker/time_picker.css'); ?>" />

<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/js/jquery.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/js/all.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/js/process.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/js/jquery.form.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/js/jquery.fancybox.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/event/date_picker/datetimepicker.js'); ?>"></script>

<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('skin/admin/event/editor/redactor.css'); ?>" />
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/event/editor/redactor.js'); ?>"></script>   

<?php /*
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('skin/admin/event/editor/flora/css/font-awesome.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('skin/admin/event/editor/flora/css/froala_editor.min.css'); ?>" />
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/event/editor/flora/js/froala_editor.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/event/editor/flora/js/plugins/tables.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/event/editor/flora/js/plugins/lists.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/event/editor/flora/js/plugins/colors.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/event/editor/flora/js/plugins/media_manager.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/event/editor/flora/js/plugins/font_family.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/event/editor/flora/js/plugins/font_size.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/event/editor/flora/js/plugins/block_styles.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/event/editor/flora/js/plugins/video.min.js'); ?>"></script>
 */ ?>
 
</head>
