<form id="grid-search-form" action="<?php echo $this->getGridUrl()?>" method="post">  
<div class="content-header">
    <table cellspacing="0">
        <tbody>
            <tr>
                <td style="width: 50%;">
                    <h3 class="icon-head head-adminhtml-admin">
                        <?php echo $this->translate('Manage Advertisements');?>
                    </h3>
                </td>
                <td class="form-buttons">
                    <button onclick="banner.setElement('main-container').setUseType('url').setURL('<?php echo $this->getCreateUrl() ?>').loadPage();" type="button" title="<?php echo $this->translate('Add New Advertisement');?>" class="scalable add">
                        <span><span><span>
                        <?php echo $this->translate('Add New Advertisement');?>
                        </span></span></span>
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div id="grid-list"></div>
</form>
<script>
var banner = new Ccc.Banner();
banner.setObject('banner');
banner.resetCheckedElements();
banner.setForm('grid-search-form');
banner.setUseType('url');
banner.setURL('<?php echo $this->getGridUrl()?>');
if(banner.getForm())
{
    banner.loadPage();
}
</script>
