<?php 
    $review = $this->getReview(); 
    $websites = $this->getWebsites();
    $object = $this->getObject();    
?>
<div class="columns ">

    <div class="side-col" id="page:left">
        <h3><?php echo $this->translate('Manage Reviews'); ?></h3>
        <ul id="page_tabs" class="tabs">
            <li>
                <a href="javascript:void(0);" class="tabHeader tab-item-link" name="main_section" title="<?php echo $this->translate('Review Information'); ?>" id="html">
                    <span><?php echo $this->translate('Review Information'); ?></span>
                </a>
            </li>
        </ul>
    </div>

    <!-- TABS START -->

    <div class="main-col" id="content">
        <div class="main-col-inner">
            <div id="messages"></div>
            <div class="content-header">
                <h3 class="icon-head head-admin-page">
                    <?php if((int)$review->review_id): ?>
                        <?php echo $this->translate('Edit Review'); ?>
                        <?php else: ?>
                        <?php echo $this->translate('Add Review'); ?>
                        <?php endif; ?>
                </h3>

                <p class="form-buttons">
                    <?php echo $this->formButton('cancel', $this->translate('Cancel'), array('class'=>'scalable', 'onclick'=>"$object.setUseType('url').setElement('main-container').setURL('".$this->getIndexJsonUrl()."').loadPage();")); ?>
                    <?php echo $this->formButton('submit', $this->translate('Save'), array('class'=>'scalable save', 'onclick'=>"$object.setForm('review_frm').setElement('main-container').setFormURL('".$this->getSaveUrl()."').saveReview(); return false;  ")); ?>
                </p>
            </div>

            <div class="entry-edit">
                <form id="review_frm" name='review_frm' action="<?php echo $this->url(array('action'=>'save')); ?>" method="post">
                    <div class="tabContent" style="display: none;">
                        <div class="entry-edit">
                            <div class="entry-edit-head">
                                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->translate('Review Information'); ?></h4>
                                <div class="form-buttons"></div>
                            </div>
                            <div class="fieldset " id="page_base_fieldset">
                                <div class="hor-scroll">
                                    <table class="form-list" cellspacing="0">
                                        <tbody>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Website'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <?php echo $this->FormSelect('review[website_id]',$review->website_id, array('class'=>'input-select'),$websites);?>
                                                    <div id="website_id" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Name'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <?php echo $this->FormText('review[name]',$this->escape($review->name), array('class'=>'input-text', 'maxlength'=>255)) ;?>
                                                    <div id="name" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Review'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <textarea cols="3" rows="3" name="review[review]"><?php echo $this->escape($review->review)?></textarea>
                                                    <div id="review" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Is Approved'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <?php echo $this->FormSelect('review[approved]',$review->approved, array('class'=>'input-select'),$this->getIsApprovedOptions());?>
                                                    <div id="approved" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                            
                                         </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div> 
                    </form>
            </div>
        </div>
    </div>
    <!-- TABS END -->
</div>

<script>


var tabObject = new Core.Tab();
jQuery(document).ready(function()
{
    tabObject.setupTab();
});    
</script>