<?php 
$websites = $this->getCollection();    
$object = $this->getObject();
?>
<input type="hidden" name="selectedIds" id="selectedIds" value=""/>
<div>
    <div>
        <table class="actions" cellspacing="0">
            <tbody>
                <tr>
                    <td class="pager">
                        <?php if($websites): ?>
                            <?php echo $this->paginationControl($websites, 'Sliding', 'pages/html/pager.phtml'); ?>
                        <?php endif;?>
                    </td>
                    <td class="filter-actions a-right">
                        
                        <?php
                            if(count($websites))
                            {
                            echo $this->formButton('delete', $this->translate('Delete'), array('class'=>'scalable', 'onclick'=>"$object.setFormURL('".$this->getDeleteUrl()."').setMessage('".$this->translate('Please select item which you want to delete.')."').confirmDelete('Are you sure you want to delete these records?');")); 
                            }
                        ?>

                        <button id="" title="Reset Filter" type="button" class="scalable " onclick="<?php echo $object; ?>.setFormURL('<?php echo $this->getResetUrl()?>').loadPage();">
                            <span><span><span><?php echo $this->translate('Reset Filter')?></span></span></span>
                        </button>
                        <button title="Search" type="submit" class="scalable" style="" onclick="<?php echo $object; ?>.setFormURL('<?php echo $this->getGridUrl()?>').loadPage(); return false;">
                            <span><span><span><?php echo $this->translate('Search')?></span></span></span>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
        
        <div id="periodGrid_massaction">
            <table class="massaction" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td>
                            <a href="javascript:void(0);" onclick="<?php echo $object; ?>.selectAll()">Select All</a>
                            <span class="separator">|</span>
                            <a href="javascript:void(0);" onclick="<?php echo $object; ?>.unselectAll()">Unselect All</a>
                            <span class="separator">|</span>
                            <a href="javascript:void(0);" onclick="<?php echo $object; ?>.selectVisible()">Select Visible</a>
                            <span class="separator">|</span>
                            <a href="javascript:void(0);" onclick="<?php echo $object; ?>.unselectVisible()">Unselect Visible</a>
                            <span class="separator">|</span>
                            <span id="row-count">0</span>
                             items selected
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        
        <div class="grid">
            <div class="hor-scroll">
                <table class="data" id="periodGrid_table" cellspacing="0">
                    <colgroup>
                        <col class="a-center" width="50">
                        <col width="50">
                        <col width="100">
                        <col width="">
                        <col width="">
                        <col width="100">
                        <col width="150">
                        <col width="60">
                    </colgroup>
                    <thead>
                        <tr class="headings">
                            <th class="no-link">
                                <span class="nobr">&nbsp;</span>
                            </th>
                            <th class="no-link">
                                <span class="nobr">Store Thumbnail</span>
                            </th>
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('ID'),'W.website_id') ?></span>
                            </th>
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('Store Name'),'W.name') ?></span>
                            </th>
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('Store URL'),'W.website_url') ?></span>
                            </th>
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('View Count'),'W.view_count') ?></span>
                            </th>
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->translate('Coupons & Deals'); ?></span>
                            </th> 
                            <th class="no-link last">
                                <span class="nobr"><?php echo $this->translate('Action'); ?></span>
                            </th>
                        </tr>
                        <tr class="filter">
                            <th></th>
                            <th></th>
                            <th>
                                <div class="field-100">
                                    <table width="160" cellpadding="0" cellspacing="0">
                                        <tr>
                                            <td valign="top"><?php echo $this->translate('From:')?></td>
                                            <td><?php echo $this->formText("website_id_from",$this->search()->website_id_from, array('class'=>'input-text', 'maxlength'=>11)); ?></td>
                                        </tr>
                                        <tr>
                                            <td valign="top"><?php echo $this->translate('To:')?></td>
                                            <td><?php echo $this->formText("website_id_to", $this->search()->website_id_to, array('class'=>'input-text', 'maxlength'=>11)); ?></td>
                                        </tr>
                                    </table>
                                </div>                                
                            </th>
                            <th>
                                <div class="field-100">
                                    <?php echo $this->formText("name", $this->search()->name, array('class'=>'input-text', 'maxlength'=>254)); ?>
                                </div>
                            </th>
                            <th>
                                <div class="field-100">
                                    <?php echo $this->formText("website_url", $this->search()->website_url, array('class'=>'input-text', 'maxlength'=>254)); ?>
                                </div>
                            </th>
                            <th>
                               <div class="field-100">
                                    <table width="160" cellpadding="0" cellspacing="0">
                                        <tr>
                                            <td valign="top"><?php echo $this->translate('From:')?></td>
                                            <td><?php echo $this->formText("view_count_from",$this->search()->view_count_from, array('class'=>'input-text', 'maxlength'=>11)); ?></td>
                                        </tr>
                                        <tr>
                                            <td valign="top"><?php echo $this->translate('To:')?></td>
                                            <td><?php echo $this->formText("view_count_to", $this->search()->view_count_to, array('class'=>'input-text', 'maxlength'=>11)); ?></td>
                                        </tr>
                                    </table>
                                </div>
                            </th>
                            <th></th> 
                            <th class=" no-link last">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if(count($websites)): ?>
                            <?php $cnt = 0; ?>
                            <?php foreach($websites as $_website): ?>
                            <tr class="<?php if(($cnt+1)%2==0): ?>odd<?php else:?>even<?php endif; ?> pointer">
                                <td class="a-center ">
                                    <?php echo $this->formCheckbox("check_single[]", $_website->website_id, array('class'=>'check_single input-checkbox','id'=>'check_single checkbox-id-'.$_website->website_id,'onclick'=>"$object.checkSingle(this)")); ?>
                                </td>
                                <td><img src="<?php echo $this->getIconImageUrl($_website); ?>" alt="<?php echo $_category->name; ?>" width="50" height="50"></td>
                                <td class="a-right "><?php echo $this->escape($_website->website_id); ?></td>
                                <td class="a-left "><?php echo $this->escape($_website->name); ?></td>
                                <td class="a-left "><?php echo $this->escape($_website->website_url); ?></td>
                                <td class="a-left "><?php echo (int)$_website->view_count; ?></td>
                                <td class="a-left ">
                                    <a class="link" href="javascript:void(0);" onclick="<?php echo $object; ?>.setElement('main-container').setUseType('url').setURL('<?php echo $this->getWebsiteWiseCouponUrl($_website); ?>').loadPage();" ><?php echo "Coupons & Deals (".$this->getCouponCountByWebsite($_website).")"?></a>
                                </td>   
                                <td class="a-center last">
                                    <a class="link" href="javascript:void(0);" onclick="<?php echo $object; ?>.setElement('main-container').setUseType('url').setURL('<?php echo $this->getEditUrl($_website); ?>').loadPage();" title="<?php echo $this->translate('Edit')?>"><img src="<?php echo $this->baseUrl('skin/admin/images/edit.png')?>"/></a>
                                </td>
                            </tr>
                            <?php $cnt++; ?>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>
                                <td class="grid-column center no-record" colspan="14">
                                <?php echo $this->translate('Stores are not available.');?>
                                </td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                </table>            
            </div>
       </div>
    </div>
</div>

<script>
var elements = <?php echo json_encode($this->getAllIds()); ?>;
<?php echo $object; ?>.setAllElements(elements);
<?php echo $object; ?>.checkVisibleCheckbox(true);
<?php echo $object; ?>.printCheckedElementCount();
</script>