<form id="grid-search-form" action="<?php echo $this->getGridUrl()?>" method="post">  
<div class="content-header">
    <table cellspacing="0">
        <tbody>
            <tr>
                <td style="width: 50%;">
                    <h3 class="icon-head head-adminhtml-admin">
                        <?php echo $this->translate('Manage Pages');?>
                    </h3>
                </td>
                <td class="form-buttons">
                    <button onclick="page.setElement('main-container').setUseType('url').setURL('<?php echo $this->getCreateUrl() ?>').loadPage();" type="button" title="<?php echo $this->translate('Add New Page');?>" class="scalable add">
                        <span><span><span>
                        <?php echo $this->translate('Add New Page');?>
                        </span></span></span>
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div id="grid-list"></div>
</form>
<script>
var page = new Ccc.Page();
page.setObject('page');
page.resetCheckedElements();
page.setForm('grid-search-form');
page.setUseType('url');
page.setURL('<?php echo $this->getGridUrl()?>');
if(page.getForm())
{
    page.loadPage();
}
</script>