<div class="header-top">
    <a href="javascript:void(0)">
        <img src="<?php echo $this->baseUrl('skin/admin/images/logo.png');?>" alt="Website Logo" class="logo">
    </a>
    <div class="header-right">
        <p class="super">
            <?php
                echo Ccc::getModel('admin/admin')->getUsername();
            ?>
            <span class="separator">|</span>
            <?php echo date('l, d F Y'); ?>
            <span class="separator">|</span>
            <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'process-logout')) ?>" class="link-logout">Log Out</a>
        </p>
    </div>
</div>

<div class="clear"></div>