<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<?php echo $this->headTitle();?>

<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('skin/admin/css/style.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('skin/admin/css/ui-lightness/jquery-ui-1.10.0.custom.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('skin/admin/event/date_picker/time_picker.css'); ?>" />

<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/js/jquery.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/js/all.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/admin/event/date_picker/datetimepicker.js'); ?>"></script>

</head>
