<?php $cache = $this->getCacheData();
$object = $this->getObject();
?>
<div class="columns ">
    
    <div class="side-col" id="page:left">
        <h3><?php echo $this->translate('Manage Caches'); ?></h3>
        <ul id="page_tabs" class="tabs">
            <li>
                <a href="javascript:void(0);" class="tabHeader tab-item-link" name="main_section" title="<?php echo $this->translate('Cache Information'); ?>" id="html">
                <span><?php echo $this->translate('Cache Information'); ?></span>
                </a>
            </li>
        </ul>
    </div>
    
    <!-- TABS START -->
    
    <div class="main-col" id="content">
        <div class="main-col-inner">
            <div id="messages"></div>
            <div class="content-header">
                <h3 class="icon-head head-cache-page">
                    <?php if($cache->cache_id): ?>
                        <?php echo $this->translate('Edit Cache'); ?>
                    <?php else: ?>
                        <?php echo $this->translate('Add Cache'); ?>
                    <?php endif; ?>
                </h3>
                <p class="form-buttons">
                    <?php echo $this->formButton('cancel', $this->translate('Cancel'), array('class'=>'scalable', 'onclick'=>"$object.setUseType('url').setElement('main-container').setURL('".$this->getIndexJsonUrl()."').loadPage();")); ?>
                    <?php echo $this->formButton('submit', $this->translate('Save'), array('class'=>'scalable save', 'onclick'=>"$object.setForm('cache_frm').setElement('main-container').setFormURL('".$this->getSaveUrl($cache)."').loadPage(); return false; ")); ?>
                </p>
            </div>
            
            <div class="entry-edit">
                <form id="cache_frm" action="<?php echo $this->getSaveUrl(); ?>" method="post" >
                    <div class="tabContent" style="display: none;">
                        <div class="entry-edit">
                            <div class="entry-edit-head">
                                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->translate('Cache Information'); ?></h4>
                                <div class="form-buttons"></div>
                            </div>
                            <div class="fieldset " id="page_base_fieldset">
                                <div class="hor-scroll">
                                    
                                    <table class="form-list" cellspacing="0">
                                        <tbody>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Name'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <?php echo $this->formText('cache[name]', $this->escape($cache->name), array('class'=>'input-text', 'maxlength'=>100)); ?>
                                                    <div id="name" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Code'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <?php echo $this->formText('cache[code]',$this->escape($cache->code), array('class'=>'input-text')); ?>
                                                    <div id="code" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Prefix'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <?php echo $this->formText('cache[prefix]', $this->escape($cache->prefix), array('class'=>'input-text')); ?>
                                                    <div id="prefix" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Lifetime'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <?php echo $this->formText('cache[lifetime]',$this->escape($cache->lifetime), array('class'=>'input-text')); ?>
                                                    <div id="lifetime" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Tag'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <?php echo $this->formText('cache[tag]',$this->escape($cache->tag), array('class'=>'input-text')); ?>
                                                    <div id="tag" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>

                                        </tbody>
                                    </table>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- TABS END -->
    
</div>

<script>
var tabObject = new Core.Tab();
jQuery(document).ready(function()
{
    tabObject.setupTab();
});
</script>