<?php 
    $menu = $this->getMenu(); 
    $object = $this->getObject();    
?>
<div class="columns ">

    <div class="side-col" id="page:left">
        <h3><?php echo $this->translate('Manage Footer Links'); ?></h3>
        <ul id="page_tabs" class="tabs">
            <li>
                <a href="javascript:void(0);" class="tabHeader tab-item-link" name="main_section" title="<?php echo $this->translate('Footer Link Information'); ?>" id="html">
                    <span><?php echo $this->translate('Footer Link Information'); ?></span>
                </a>
            </li>
        </ul>
    </div>

    <!-- TABS START -->

    <div class="main-col" id="content">
        <div class="main-col-inner">
            <div id="messages"></div>
            <div class="content-header">
                <h3 class="icon-head head-admin-page">
                    <?php if((int)$menu->id): ?>
                        <?php echo $this->translate('Edit Footer Link'); ?>
                        <?php else: ?>
                        <?php echo $this->translate('Add Footer Link'); ?>
                        <?php endif; ?>
                </h3>

                <p class="form-buttons">
                    <?php echo $this->formButton('cancel', $this->translate('Cancel'), array('class'=>'scalable', 'onclick'=>"$object.setUseType('url').setElement('main-container').setURL('".$this->getIndexJsonUrl()."').loadPage();")); ?>
                    <?php echo $this->formButton('submit', $this->translate('Save'), array('class'=>'scalable save', 'onclick'=>"$object.setForm('menu_frm').setElement('main-container').setFormURL('".$this->getSaveUrl()."').saveMenu(); return false;  ")); ?>
                </p>
            </div>

            <div class="entry-edit">
                <form id="menu_frm" name='menu_frm' action="<?php echo $this->url(array('action'=>'save')); ?>" method="post">
                    <div class="tabContent" style="display: none;">
                        <div class="entry-edit">
                            <div class="entry-edit-head">
                                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->translate('Footer Link Information'); ?></h4>
                                <div class="form-buttons"></div>
                            </div>
                            <div class="fieldset " id="page_base_fieldset">
                                <div class="hor-scroll">
                                    <table class="form-list" cellspacing="0">
                                        <tbody>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Menu Label'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <?php echo $this->FormText('menu[label]',$this->escape($menu->label), array('class'=>'input-text', 'maxlength'=>255)) ;?>
                                                    <div id="label" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Menu Title'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <?php echo $this->FormText('menu[title]',$this->escape($menu->title), array('class'=>'input-text', 'maxlength'=>255)) ;?>
                                                    <div id="title" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Page'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                       <select name="menu[page_id]" id="menu_page" class="input-select">
                                                        <option value="0">No Page</option>
                                                       
                                                <?php $pages = $this->getPages(); ?>
                                                <?php if(count($pages)) : ?>
                                                    <?php foreach($pages as $_page) : ?>
                                                        <?php if($menu->page_id == $_page["page_id"]): ?>
                                                            <option selected="selected" value="<?php echo $_page["page_id"]?>" id="<?php echo $_page["url_key"]?>"><?php echo $_page["name"]?></option>
                                                        <?php else: ?>
                                                            <option value="<?php echo $_page["page_id"]?>" id="<?php echo $_page["url_key"]?>"><?php echo $_page["name"]?></option>
                                                        <?php endif; ?>
                                                    <?php endforeach; ?>
                                                <?php endif; ?>
                                                    <?php //echo $this->FormSelect('menu[page_id]',$menu->page_id, array('class'=>'input-select', 'id'=>'menu_page'), array(0=>"No Page")+$this->getPages());?>
                                                    </select>
                                                    <div id="page_id" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Menu URL'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <?php echo $this->FormText('menu[url]',$this->escape($menu->url), array('class'=>'input-text', 'id'=>'menu_url', 'maxlength'=>255)) ;?>
                                                    <div id="url" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Position'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <?php echo $this->FormText('menu[sort_order]',$this->escape($menu->sort_order), array('class'=>'input-text', 'maxlength'=>255)) ;?>
                                                    <div id="sort_order" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Active'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <?php echo $this->FormSelect('menu[is_enabled]',$menu->is_enabled, array('class'=>'input-select'),$this->getIsEnabledOptions());?>
                                                    <div id="is_enabled" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Show In Section'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <?php echo $this->FormSelect('menu[is_quicklink]',$menu->is_quicklink, array('class'=>'input-select'),$this->getQuickLinkOptions());?>
                                                    <div id="is_enabled" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                         </tbody>
                                    </table>
                                </div>                                     
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- TABS END -->
</div>

<script>
var tabObject = new Core.Tab();
jQuery(document).ready(function()
{
    tabObject.setupTab();
    
    jQuery("#menu_page").change(function(){
        
            var id = jQuery(this).find(':selected')[0].id;
             if(this.value == 0)
             {
                 jQuery("#menu_url").val("");
                 jQuery("#menu_url").removeAttr("readonly");
             }
             else
             {
                 jQuery("#menu_url").val(id);  
                 jQuery("#menu_url").attr("readonly", true); 
             }
    });
});
</script>