<?php $group = $this->getSystemConfigGroupData();
$object = $this->getObject();
?>
<div class="columns ">

    <div class="side-col" id="page:left">
        <h3><?php echo $this->translate('Manage System Config Group'); ?></h3>
        <ul id="page_tabs" class="tabs">
            <li>
                <a href="javascript:void(0);" class="tabHeader tab-item-link" name="main_section" title="<?php echo $this->translate('System Config Group Information'); ?>" id="html">
                <span><?php echo $this->translate('System Config Group Information'); ?></span>
                </a>
            </li>
        </ul>
    </div>

    <!-- TABS START -->
    <div class="main-col" id="content">
        <div class="main-col-inner">
            <div id="messages"></div>
            <div class="content-header">
                <h3 class="icon-head head-config_group-page">
                    <?php if($group->system_config_group_id): ?>
                        <?php echo $this->translate('Edit System Config Group'); ?>
                    <?php else: ?>
                        <?php echo $this->translate('Add System Config Group'); ?>
                    <?php endif; ?>
                </h3>
                <p class="form-buttons">
                    <?php echo $this->formButton('cancel', $this->translate('Cancel'), array('class'=>'scalable', 'onclick'=>"{$object}.setUseType('url').setElement('main-container').setURL('".$this->getIndexJsonUrl()."').loadPage();")); ?>
                    <?php echo $this->formButton('submit', $this->translate('Save'), array('class'=>'scalable save', 'onclick'=>"{$object}.setForm('grid-search-form').setElement('main-container').setFormURL('".$this->getSaveUrl($group)."').loadPage(); return false; ")); ?>
                </p>
            </div>
            
            <div class="entry-edit">
                <form id="grid-search-form" name='group_frm' action="<?php echo $this->url(array('action'=>'save')); ?>" method="post">
                    <div class="tabContent" style="display: none;">
                        <div class="entry-edit">
                            <div class="entry-edit-head">
                                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->translate('System Config Group Information'); ?></h4>
                                <div class="form-buttons"></div>
                            </div>
                            <div class="fieldset " id="page_base_fieldset">
                                <div class="hor-scroll">
                                    <table class="form-list" cellspacing="0">
                                        <tbody>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Group Name'); ?>:<span class="required">*</span>
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <?php echo $this->FormText('group[name]',$this->escape($group->name), array('class'=>'input-text', 'maxlength'=>50));?>
                                                    <div id="name" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="label">
                                                    <label for="page_title">
                                                        <?php echo $this->translate('Sort Order'); ?>:
                                                    </label>
                                                </td>
                                                <td class="value">
                                                    <?php echo $this->FormText('group[sort_order]',$this->escape($group->sort_order), array('class'=>'input-text', 'maxlength'=>10));?>
                                                    <div id="sort_order" class="messages">
                                                        <ul class="success"></ul>
                                                        <ul class="error"></ul>
                                                        <ul class="notice"></ul>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
    <!-- TABS END -->
    
</div>

<script>
var tabObject = new Core.Tab();
jQuery(document).ready(function()
{
    tabObject.setupTab();
});

</script>