<div id="store-alpha-list" style="width: 100%;">
    <div class="panel panel-default">   
        <div class="panel-heading">
          <h2 class="panel-title">Browse By Store</h2>
        </div>
        <div class="panel-body panel-row last">
          <div>
                <div class="store-alphabet-list">
                    <ul>
                        <li><p><a title="<?php echo "0-9"; ?>" href="<?php echo $this->baseUrl("stores/0-9"); ?>"><?php echo "0-9"; ?></a></p></li>    
                        <?php $letters = range('A', 'Z'); ?>
                        <?php foreach($letters as $_letter): ?>
                            <li><p><a title="<?php echo $_letter; ?>" href="<?php echo $this->baseUrl("stores/".strtolower($_letter)); ?>"><?php echo $_letter; ?></a></p></li>
                        <?php endforeach; ?>
                    </ul>
                </div> 
          </div>
        </div> 
     </div>       
</div>