<?php $headerBlock = Ccc::getBlock("user/pages_html_header"); ?>
 
<div marginheight="0" marginwidth="0" style="font-family: 'inherit';margin:0px;font-size:14px;background:#FFFFFF;border-color:#FFFFFF; border-width:1px; " >
    <table align="center" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:540px">
        <tbody>  
            <tr> 
                <td align="center" colspan="3">
                    <div style="display:block; margin-left: auto; margin-right: auto; padding: 10px; padding-top:0px; background-image:linear-gradient(to bottom, #3c3c3c 0px, #222 100%); background-repeat:repeat-x;background-color:#222; border-color:#080808; top:0; border-width:0 0 1px;">
                        <a href="<?php echo $this->cron->getHomeUrl(); ?>" title="<?php echo $this->websiteName; ?>" style="outline:none;border:none;display:block;background:0px 50%; color: #FFFFFF;" target="_blank">
                        <?php if($logo = $headerBlock->getLogoURL()): ?>
                            <img style="padding: 5px 20px;" src="<?php echo $logo; ?>" alt="<?php echo $this->websiteName; ?>">
                        <?php else: ?>
                            <label style="display : block; font-size: 25px; padding: 20px; font-style: inherit; outline: none;"><?php echo $this->websiteName; ?></label>
                        <?php endif; ?>
                        </a>
                    </div>
                </td>
            </tr>
            <tr>
                <td align="center" colspan="3">
                    <div style="font-size:15px; color:#525252; font-style:normal; border-bottom:thin dashed silver;">
                        <h1><?php echo "This Week's Top Coupons."?></h1>
                    </div>
                </td>
            </tr>
           
            <tr><td colspan="3">&nbsp;</td></tr>
            <?php $count = 0; $totalCount = count($this->coupons); ?>
            <tr> 
            <?php foreach($this->coupons as $_coupon):?>
                <?php if(($count%3 == 0) && ($count != 0)): ?>
                    </tr>
                    <?php if($count !=  $totalCount):?>
                        <tr>
                    <?php endif; ?>
                <?php endif; ?>
                    <td align="center">
                        <div style="margin:5px; background-color: #fff; border:1px solid #ccc; border-radius:4px; box-shadow:0 2px 5px rgba(0, 0, 0, 0.1), 0 0 0 transparent;">
                        <table style="width:100%;">
                                <tbody>
                                    <tr>
                                        <td align="center">
                                            <a title="<?php echo ucfirst($_coupon->website_name); ?>" href="<?php echo $this->cron->getWebsiteViewUrl($_coupon->website_id); ?>" style="color: #428bca; text-decoration: none;" target="_blank">
                                                <?php $websiteImage = Ccc::getModel("website/uploader")->getIconImageUrl($_coupon->icon); ?>
                                                <img src="<?php echo $websiteImage; ?>" alt="<?php echo ucfirst($_coupon->website_name); ?>" style="margin:10px;vertical-align:middle; padding : 2px; border:1px solid #ccc;" class="CToWUd">
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td align="center">
                                            <a title="<?php echo ucfirst($_coupon->website_name).": ".ucfirst($_coupon->name); ?>" href="<?php echo $this->cron->getCouponViewUrl($_coupon->coupon_id, $_coupon->website_id); ?>" style="color: #428bca; text-decoration: none; margin-bottom: 10px; display: block;" target="_blank">
                                                <?php echo ucfirst($_coupon->website_name).": ".ucfirst($_coupon->name); ?>
                                            </a>
                                        </td>
                                    </tr>
                            </tbody></table>
                        </div>
                    </td>
                
                <?php $count = $count + 1;?>
            <?php endforeach; ?>
            </tr>
            <tr>
                <td valign="top" align="center" colspan="3">
                    <div style="display:block; padding: 15px; background-image:linear-gradient(to bottom, #3c3c3c 0px, #222 100%); background-repeat:repeat-x;background-color:#222; border-color:#080808; top:0; border-width:0 0 1px; color: #c9c9c9;">
                          You received this email because you signed up for coupon alerts from                                
                    <a style="color:rgb(172,170,167);text-decoration:underline" href="<?php echo $this->cron->getHomeUrl(); ?>" title="<?php echo $this->websiteName; ?>" target="_blank"><?php echo $this->websiteName; ?></a>.<br>
                      Not interested anymore? <br>
                      <a title="unsubscribe" style="color:rgb(172,170,167);text-decoration:underline" href="<?php echo $this->cron->getHomeUnsubscriptionUrl(); ?>" target="_blank">Unsubscribe from <?php echo $this->websiteName; ?> coupon alerts.</a>
                    </div>
                </td>
            </tr>
        </tbody>
</table>
</div>