<?php $headerBlock = Ccc::getBlock("user/pages_html_header"); ?>
 
<div marginheight="0" marginwidth="0" style="font-family: 'inherit';margin:0px;font-size:14px;background:#FFFFFF;border-color:#FFFFFF; border-width:1px; " >
    <table align="center" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:650px;">
        <tbody>  
            <tr> 
                <td align="center" colspan="3">
                    <div style="display:block; margin-left: auto; margin-right: auto; padding: 10px; padding-top:0px; background-image:linear-gradient(to bottom, #3c3c3c 0px, #222 100%); background-repeat:repeat-x;background-color:#222; border-color:#080808; top:0; border-width:0 0 1px;">
                        <a href="<?php echo $this->cron->getHomeUrl(); ?>" title="<?php echo $this->websiteName; ?>" style="outline:none;border:none;display:block;background:0px 50%; color: #FFFFFF;" target="_blank">
                        <?php if($logo = $headerBlock->getLogoURL()): ?>
                            <img style="padding: 5px 20px;" src="<?php echo $logo; ?>" alt="<?php echo $this->websiteName; ?>">
                        <?php else: ?>
                            <label style="display : block; font-size: 25px; padding: 20px; font-style: inherit; outline: none;"><?php echo $this->websiteName; ?></label>
                        <?php endif; ?>
                        </a>
                    </div>
                </td>
            </tr>
            <tr>
                <td align="left" width="30%;">
                     <div style=" display: block; font-size:15px; color:#525252; font-style:normal;">
                     <a style=" color: #428bca; text-decoration: none;" title="<?php echo ucfirst($this->store["name"]); ?>" href="<?php echo $this->cron->getWebsiteViewUrl($this->store["website_id"]); ?>" target="_blank">
                        <?php $websiteImage = Ccc::getModel("website/uploader")->getIconImageUrl($this->store["icon"]); ?>
                        <img src="<?php echo $websiteImage; ?>" alt="<?php echo ucfirst($this->store["name"]); ?>" style="margin:10px;padding : 2px; border:1px solid #ccc;" class="CToWUd">
                     </a>
                     </div>
                </td>
                <td align="left" colspan="2">
                    <div style=" display: block; font-size:15px; color:#525252; font-style:normal;">
                    <a title="<?php echo ucfirst($this->store["name"]); ?>" href="<?php echo $this->cron->getWebsiteViewUrl($this->store["website_id"]); ?>" style="color:#428bca;text-decoration:none" target="_blank">
                            <span style="padding:0px;line-height:35px;margin:0px 0px 0px 10px;font-size:30px;font-weight:normal;color:#428bca;text-align:left"><?php echo ucfirst($this->store["name"]); ?></span><br>
                        </a>
                        <span style="padding:0px;line-height:25px;margin:0px 0px 0px 10px;font-size:20px;font-weight:normal;color:#525252;text-align:left">Popular Coupons</span>
                    </div>
                </td>
            </tr>
            <?php $count = 1; ?>
            <tr>
                <td align="left" colspan="3">
                    <table style="width:100%;">
                        <tbody>
                            <?php foreach($this->coupons as $_coupon):?>
                                <tr>
                                    <td>
                                    <div style="display:block; color:#525252; padding:12px 0; cursor:pointer; background:none repeat scroll 0 0 #fff;box-shadow:0 2px 5px rgba(0, 0, 0, 0.1), 0 0 0 transparent; border:1px solid #ccc; border-radius:4px;">
                                        &nbsp;&nbsp;<?php echo $count; ?>.&nbsp;&nbsp;<a href="<?php echo $this->cron->getCouponViewUrl($_coupon->coupon_id, $_coupon->website_id); ?>" title="<?php echo ucfirst($_coupon->name); ?>" style="text-decoration:none;color:#525252;" target="_blank"><?php echo ucfirst($_coupon->name); ?></a>
                                    </div>
                                    </td>
                                </tr>
                            <?php $count = $count + 1;?>
                            <?php endforeach; ?>
                        </tbody>
                    </table> 
                    <ul>
                        
                    </ul>
                </td>
            </tr>
            <tr>
                <td valign="top" align="center" colspan="3">
                    <div style="display:block; padding: 15px; background-image:linear-gradient(to bottom, #3c3c3c 0px, #222 100%); background-repeat:repeat-x;background-color:#222; border-color:#080808; top:0; border-width:0 0 1px; color: #c9c9c9;">
                          You received this email because you signed up for coupon alerts from                                
                    <a style="color:#428bca;text-decoration:underline" href="<?php echo $this->cron->getHomeUrl(); ?>" title="<?php echo $this->websiteName; ?>" target="_blank"><?php echo $this->websiteName; ?></a>.<br>
                      Not interested anymore? <br>
                      <a title="Unsubscribe" style="color:#428bca;text-decoration:underline" href="<?php echo $this->cron->getStoreUnsubscriptionUrl($this->store["website_id"]); ?>" target="_blank">Unsubscribe from <?php echo ucfirst($this->store["name"]); ?> coupon alerts.</a>
                    </div>
                </td>
            </tr>
        </tbody>
</table>
</div>