<div class="container landingpage_main">
    <div class="main_logo">
    <div class="errorpage">
        <h3>Whoops! Our Bad!</h3>
        <dl>
            <dt>Seems like we can't find the page you were looking for!</dt>
            <dd>Either the URL no longer exists, you mistyped the URL, or that particular page has been moved.</dd>
        </dl>
        <dl>
            <dd>Please try one of the options below:</dd>
            <dd>
                <ul class="disc">
                    <li>Try using the search feature above</li>
                    <li>Go to the<a href="<?php echo $this->baseUrl('/'); ?>">Homepage</a></li>
                    <li>Browse <a href="<?php echo $this->baseUrl('stores'); ?>">All Stores</a></li>
                </ul>
            </dd>
        </dl>
        <br>
    </div>    
</div>