<?php $header = Ccc::getBlock("user/pages_html_header"); ?>
<div class="landingpage_main">
    <div class="main_logo">
    <?php if($url = $header->getLogoURL()): ?>
    <a href="<?php echo $header->getHomeUrl(); ?>"><img src="<?php echo $header->getLogoURL(); ?>" alt="<?php echo $header->getWebsiteName(); ?>"></a>
  <?php else: ?>
    <a class="navbar-brand" href="<?php echo $header->getHomeUrl(); ?>"><?php echo $header->getWebsiteName(); ?></a>
  <?php endif; ?>
    <div class="errorpage">
        <h3><?php echo $this->translate('Whoops, our bad...');?></h3>
        <dl>
            <dt>The page you requested was not found, and we have a fine guess why.</dt>
            <dd>
                <ul class="disc">
                    <li>If you typed the URL directly, please make sure the spelling is correct.</li>
                    <li>If you clicked on a link to get here, the link is outdated.</li>
                </ul>
            </dd>
        </dl>
        <br>
        <dl>
            <dt>What can you do?</dt>
            <dd>There are many ways you can get back on track with <?php echo ucfirst($header->getWebsiteName()); ?>.</dd>
            <dd>
                <ul class="disc">
                    <li><a href="<?php echo $this->baseUrl('/'); ?>">Go back</a> to the previous page.</li>
                    <li>Follow these links to get you back on track!<br><a href="<?php echo $this->baseUrl('/'); ?>">Home</a></li>
                </ul>
            </dd>
        </dl>
        <br>
    </div>    
</div>