<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php //echo $this->render('pages/html/head.phtml'); ?>
<?php echo Ccc::getBlock("admin/pages_html_head")->toHtml();?>
<body>
<?php //echo $this->render('pages/html/container.phtml'); ?>
<?php echo Ccc::getBlock("admin/pages_html_container")->toHtml();?>
</body>
</html>
