<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" >
<?php echo Ccc::getBlock("user/pages_html_head")->toHtml(); ?>
<body role="document">
    <div class="main">
        <?php echo Ccc::getBlock("user/pages_html_header")->toHtml();?>
        <?php echo Ccc::getBlock("user/pages_html_message")->toHtml(); ?>
        <div id="main-content" role="main" class="container theme-showcase"><?php echo Ccc::getBlock("user/pages_html_content")->toHtml(); ?></div>
        <?php echo Ccc::getBlock("user/pages_html_footer")->toHtml(); ?>
    </div>
</body>
</html>

