<form id="grid-search-form" action="<?php echo $this->getGridUrl()?>" method="post">  
<div class="content-header">
    <table cellspacing="0">
        <tbody>
            <tr>
                <td style="width: 50%;">
                    <h3 class="icon-head head-adminhtml-config">
                        <?php echo $this->translate('Manage General Settings');?>
                    </h3>
                </td>
                <td class="form-buttons">
                    <button onclick="systemConfig.setForm('config_frm').setElement('main-container').setUseType('form').setURL('<?php echo $this->getSaveUrl() ?>').saveConfig();" type="button" title="<?php echo $this->translate('Save');?>" class="scalable">
                        <span><span><span>
                        <?php echo $this->translate('Save');?>
                        </span></span></span>
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div id="grid-list"></div>
</form>
<script>
var systemConfig = new Ccc.System_Config();
systemConfig.setObject('systemConfig');
systemConfig.resetCheckedElements();
systemConfig.setForm('grid-search-form');
systemConfig.setUseType('url');
systemConfig.setURL('<?php echo $this->getGridUrl()?>');
if(systemConfig.getForm())
{
    systemConfig.loadPage();
}
</script>