<?php $coupon = $this->getCouponData(); ?>

<div class="coupon-popup">
    <div class="col-100" style="margin-bottom: 2%;">
        <img class="coupon-poup-close" src="<?php echo $this->baseUrl("skin/front/images/icons/popup-close.png"); ?>" alt="Close Popup"/>
        <p class="couponDatePopup">
            <?php if($coupon["end_date"] = (string)trim($coupon["end_date"])): ?>
              <?php if(strtotime($coupon["end_date"]) > strtotime(date("Y-m-d"))): ?>
                    <span><solid><strong><font color="green"><?php echo ($coupon["type"]== Coupon_Model_Coupon::COUPON_TYPE_CODE)?"COUPON":"DEAL";?> VALID UNTIL</font></strong></solid>:</span><time datetime="<?php echo date("Y-m-d", strtotime($coupon["end_date"])); ?>"><?php echo date("d F, Y", strtotime($coupon["end_date"])); ?></time>
              <?php else: ?>
                   <strong><solid><font color="#FFBF00">ONGOING OFFER</font></solid></strong>
              <?php endif; ?>
          <?php else: ?>
                 <strong><solid><font color="#FFBF00">ONGOING OFFER</font></solid></strong>
          <?php endif; ?>
        </p>
        <p class="couponNamePopup"><?php echo $coupon["name"];?></p>
        <span class="standardPopupCodeDescription">
            <?php echo $coupon["short_description"]; ?>
        </span>
    </div>
    
    <div class="col-100">
        <div class="popupShopImage">
        <img src="<?php echo Ccc::getModel("website/uploader")->getIconImageUrl($coupon["website_icon"]); ?>" alt="<?php echo ucfirst($coupon["website_name"]); ?>" title="<?php echo ucfirst($coupon["website_name"]); ?>"/>
        </div>
        <div class="popupTextContent">
            <div class="codeFrameLabel">
                <div class="popup-couponcode" id="text-to-copy"><?php echo "No coupon code required"; ?></div>               
            </div>
            <div class="gotosite">
                <button class="btn btn-lg btn-primary btn-block btn-header-search popup-btn-redirect" type="button" title="Click for discount" onclick="window.open('<?php echo Ccc::getModel("core/url_rewrite")->getRedirectUrlByEntity($coupon["coupon_id"], Core_Model_Url_Rewrite::ENTITY_COUPON); ?>','_blank');">Go to the Site</button>
            </div>
        </div>
    </div>
    <div style="clear: both;"></div>
    <div class="col-100" style="margin-top: 1%;">
        <?php if($coupon["terms_condition"]): ?>
        <div class="termsAndCondition" style="float: left; margin-right: 1%;">
            <a class="coupon-termsAndConditions popup-termsAndCondition" data-ga-act="load" data-ga="termsAndConditions" title="Terms and Conditions" id="opened-popup" href="javascript:void(0);">Terms and Conditions</a>
        </div>
        <?php endif; ?>
        
        <div class="popup-bottom">
            The stores website has been opened in a new tab.
        </div>
        <div class="clear:both;"></div>
        <?php if($coupon["terms_condition"]): ?> 
            <div class="termsDescription popuptermsDescription" id="opened-popup-description"><?php echo $coupon["terms_condition"]; ?></div>
    <?php endif; ?> 
    </div>
</div>

<script>
    var couponId = "<?php echo $coupon["coupon_id"]; ?>";
    jQuery(".copy-button").zclip({ path: "<?php echo $this->baseUrl('skin/front/js/');?>ZeroClipboard.swf", copy: function(){ return $(this).prev().val(); } });
    
    jQuery(".coupon-poup-close").click(function(){
       jQuery('#btn-popup-'+couponId).popup('hide');
    });
</script>
    
