<form id="grid-search-form" action="<?php echo $this->getGridUrl()?>" method="post">  
<div class="content-header">
    <table cellspacing="0">
        <tbody>
            <tr>
                <td style="width: 50%;">
                    <h3 class="icon-head head-adminhtml-admin">
                        <?php echo $this->translate('Manage Tags');?>
                    </h3>
                </td>
                <td class="form-buttons">
                    <button onclick="tag.setElement('main-container').setUseType('url').setURL('<?php echo $this->getCreateUrl() ?>').loadPage();" type="button" title="<?php echo $this->translate('Add New Tag');?>" class="scalable add">
                        <span><span><span>
                        <?php echo $this->translate('Add New Tag');?>
                        </span></span></span>
                    </button>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<div id="grid-list"></div>
</form>
<script>
var tag = new Ccc.Tag();
tag.setObject('tag');
tag.resetCheckedElements();
tag.setForm('grid-search-form');
tag.setUseType('url');
tag.setURL('<?php echo $this->getGridUrl()?>');
if(tag.getForm())
{
    tag.loadPage();
}
</script>