<?php $crons = $this->getCollection();?>
<input type="hidden" name="selectedIds" id="selectedIds" value=""/>
<div>
    <div>
        <table class="actions" cellspacing="0">
            <tbody>
                <tr>
                    <td class="pager">
                        <?php if($crons): ?>
                            <?php echo $this->paginationControl($crons, 'Sliding', 'pages/html/pager.phtml'); ?>
                        <?php endif;?>
                    </td>
                    <td class="filter-actions a-right">
                        <?php if(count($crons))  echo $this->formButton('delete', $this->translate('Delete'), array('class'=>'scalable', 'onclick'=>"object.setFormURL('".$this->getDeleteUrl()."').setMessage('".$this->translate('Please select cron which you want to delete.')."').confirmDelete('".$this->translate('Are you sure you want to delete these records?')."');")); ?> 
                        <button id="" title="Reset Filter" type="button" class="scalable " onclick="object.setFormURL('<?php echo $this->getResetUrl()?>').loadPage();">
                            <span><span><span><?php echo $this->translate('Reset Filter')?></span></span></span>
                        </button>
                        <button title="Search" type="submit" class="scalable" style="" onclick="object.setFormURL('<?php echo $this->getGridUrl()?>').loadPage(); return false;">
                            <span><span><span><?php echo $this->translate('Search')?></span></span></span>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
        
        <div id="periodGrid_massaction">
            <table class="massaction" cellpadding="0" cellspacing="0">
                <tbody>
                    <tr>
                        <td>
                            <a href="javascript:void(0);" onclick="object.selectAll()">Select All</a>
                            <span class="separator">|</span>
                            <a href="javascript:void(0);" onclick="object.unselectAll()">Unselect All</a>
                            <span class="separator">|</span>
                            <a href="javascript:void(0);" onclick="object.selectVisible()">Select Visible</a>
                            <span class="separator">|</span>
                            <a href="javascript:void(0);" onclick="object.unselectVisible()">Unselect Visible</a>
                            <span class="separator">|</span>
                            <span id="row-count">0</span>
                            <!--<input style="width: 50px;" disabled="disabled" type="text" name="row-count" value="0" id="row-count"/>--> items selected
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        
        <div class="grid">
            <div class="hor-scroll">
                <table class="data" id="periodGrid_table" cellspacing="0">
                    <colgroup>
                        <col class="a-center" width="50">
                        <col class="a-center" width="110">
                        <col width="150">
                        <col width="150">
                        <col>
                        <col>
                        <col>
                        <col>
                    </colgroup>
                    <thead>
                        <tr class="headings">
                            <th>&nbsp;
                                
                            </th>
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('ID'),'CSM.schedule_id') ?></span>
                            </th>
                            
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('Job Code'),'CM.job_code') ?></span>
                            </th>
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('Status'),'CSM.status') ?></span>
                            </th>   
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('Messages'),'CSM.messages') ?></span>
                            </th>
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('Scheduled On'),'CSM.scheduled_at') ?></span>
                            </th>
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('Executed On'),'CSM.executed_at') ?></span>
                            </th>      
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('Finished On'),'CSM.finished_at') ?></span>
                            </th>      
                            <th class="no-link">
                                <span class="nobr"><?php echo $this->getHeaderHtml($this->translate('Created On'),'CSM.created_at') ?></span>
                            </th>      
                        </tr>
                        <tr class="filter">
                            <th>&nbsp;
                                
                            </th>
                            <th style="display: none;">
                                <?php 
                                if(count($crons)):
                                    echo $this->formCheckbox("checkAll", null, array('class'=>'checkAll input-checkbox'));
                                else:
                                    echo $this->formCheckbox("checkAll", null, array('class'=>'checkAll input-checkbox', 'disabled'=>'disabled'));
                                endif;
                                ?>
                            </th>
                            <th>
                                <div class="field-100">
                                    <table width="160" cellpadding="0" cellspacing="0">
                                        <tr>
                                            <td valign="top"><?php echo $this->translate('From:'); ?></td>
                                            <td><?php echo $this->formText("schedule_id_from", $this->search()->schedule_id_from, array('class'=>'input-text', 'maxlength'=>11)); ?></td>
                                        </tr>
                                        <tr>
                                            <td valign="top"><?php echo $this->translate('To:'); ?></td>
                                            <td><?php echo $this->formText("schedule_id_to", $this->search()->schedule_id_to, array('class'=>'input-text', 'maxlength'=>11)); ?></td>
                                        </tr>         
                                    </table>
                                </div>
                            </th>
                             
                            <th>
                                <div class="field-100">
                                    <?php echo $this->formText("job_code", $this->search()->job_code, array('class'=>'input-text', 'maxlength'=>50)); ?>
                                </div>
                            </th>
                            <th>
                                <div class="field-100">
                                    <?php echo $this->formText("status", $this->search()->status, array('class'=>'input-text', 'maxlength'=>50)); ?>
                                </div>
                            </th>
                            <th>
                                <div class="field-100">
                                    <?php echo $this->formText("messages", $this->search()->messages, array('class'=>'input-text', 'maxlength'=>50)); ?>
                                </div>
                            </th>
                            <th>
                                <div class="field-100">
                                <table width="160" cellpadding="0" cellspacing="0">
                                    <tr>
                                        <td valign="top"><?php echo $this->translate('From:')?></td>
                                        <td><?php echo $this->formText("scheduled_at_from", $this->search()->scheduled_at_from, array('id'=>'created_from_date', 'class'=>'w2em format-y-m-d divider-dash input-text', 'readonly'=>'readonly', 'style'=>'width: 90px; align:center; vertical-align: middle;')); ?></td>
                                    </tr>
                                    <tr>
                                        <td valign="top"><?php echo $this->translate('To:')?></td>
                                        <td><?php echo $this->formText("scheduled_at_to", $this->search()->scheduled_at_to, array('id'=>'created_to_date', 'class'=>'w2em format-y-m-d divider-dash input-text', 'readonly'=>'readonly', 'style'=>'width: 90px; align:center; vertical-align: middle;')); ?></td>
                                    </tr>
                                </table>
                                </div>
                            </th>
                            <th>
                                <div class="field-100">
                                <table width="160" cellpadding="0" cellspacing="0">
                                    <tr>
                                        <td valign="top"><?php echo $this->translate('From:')?></td>
                                        <td><?php echo $this->formText("executed_at_from", $this->search()->executed_at_from, array('id'=>'created_from_date', 'class'=>'w2em format-y-m-d divider-dash input-text', 'readonly'=>'readonly', 'style'=>'width: 90px; align:center; vertical-align: middle;')); ?></td>
                                    </tr>
                                    <tr>
                                        <td valign="top"><?php echo $this->translate('To:')?></td>
                                        <td><?php echo $this->formText("executed_at_to", $this->search()->executed_at_to, array('id'=>'created_to_date', 'class'=>'w2em format-y-m-d divider-dash input-text', 'readonly'=>'readonly', 'style'=>'width: 90px; align:center; vertical-align: middle;')); ?></td>
                                    </tr>
                                </table>
                                </div>
                            </th>
                            <th>
                                <div class="field-100">
                                <table width="160" cellpadding="0" cellspacing="0">
                                    <tr>
                                        <td valign="top"><?php echo $this->translate('From:')?></td>
                                        <td><?php echo $this->formText("finished_at_from", $this->search()->finished_at_from, array('id'=>'created_from_date', 'class'=>'w2em format-y-m-d divider-dash input-text', 'readonly'=>'readonly', 'style'=>'width: 90px; align:center; vertical-align: middle;')); ?></td>
                                    </tr>
                                    <tr>
                                        <td valign="top"><?php echo $this->translate('To:')?></td>
                                        <td><?php echo $this->formText("finished_at_to", $this->search()->finished_at_to, array('id'=>'created_to_date', 'class'=>'w2em format-y-m-d divider-dash input-text', 'readonly'=>'readonly', 'style'=>'width: 90px; align:center; vertical-align: middle;')); ?></td>
                                    </tr>
                                </table>
                                </div>
                            </th>
                            <th>
                                <div class="field-100">
        
                                <table width="160" cellpadding="0" cellspacing="0">
                                    <tr>
                                        <td valign="top"><?php echo $this->translate('From:')?></td>
                                        <td><?php echo $this->formText("created_at_from", $this->search()->created_at_from, array('id'=>'updated_from_date', 'class'=>'w2em format-y-m-d divider-dash input-text', 'readonly'=>'readonly', 'style'=>'width: 90px; align:center; vertical-align: middle;')); ?></td>
                                    </tr>
                                    <tr>
                                        <td valign="top"><?php echo $this->translate('To:')?></td>
                                        <td><?php echo $this->formText("updated_at_to", $this->search()->created_at_to, array('id'=>'updated_to_date', 'class'=>'w2em format-y-m-d divider-dash input-text', 'readonly'=>'readonly', 'style'=>'width: 90px; align:center; vertical-align: middle;')); ?></td>
                                    </tr>
                                </table>
                                </div>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if(count($crons)): ?>
                            <?php $cnt = 0; ?>
                            <?php foreach($crons as $_item): ?>
                                <tr class="<?php if(($cnt+1)%2==0): ?>odd<?php else:?>even<?php endif; ?> pointer">
                                    <td class="a-center ">
                                        <?php echo $this->formCheckbox("cron_schedule[]", $_item->schedule_id, array('class'=>'check_single input-checkbox','id'=>'check_single checkbox-id-'.$_item->schedule_id,'onclick'=>"object.checkSingle(this)")); ?>
                                    </td>
                                    <td class="a-right"><?php echo $this->escape($_item->schedule_id); ?></td>
                                    
                                    <td class="a-left"><?php echo $this->escape($_item->job_code); ?></td>
                                    <td class="a-left"><?php echo $this->escape($_item->status); ?></td>
                                    <td class="a-left"><?php echo $this->escape($_item->messages); ?></td>
                                    <td class="a-center"><?php echo $this->date()->getFormattedDateView($_item->scheduled_at); ?></td>
                                    <td class="a-center"><?php echo $this->date()->getFormattedDateView($_item->executed_at); ?></td>
                                    <td class="a-center"><?php echo $this->date()->getFormattedDateView($_item->finished_at); ?></td>
                                    <td class="a-center"><?php echo $this->date()->getFormattedDateView($_item->created_at); ?></td>
                                </tr>
                                <?php $cnt++; ?>
                            <?php endforeach; ?>
                        <?php else: ?>
                            <tr>
                                <td class="grid-column center no-record" colspan="9">
                                <?php echo $this->translate('No records available.');?>
                                </td>
                            </tr>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
       </div>
    </div>
</div>

<script>

var elements = <?php echo json_encode($this->getAllIds()); ?>;

object.setAllElements(elements);
object.checkVisibleCheckbox(true);
object.printCheckedElementCount();

</script>

<script type="text/javascript">
jQuery('#birth_date').datepicker({
    dateFormat : 'yy-mm-dd',
    changeMonth : true,
    yearRange   : '-90:+0',
    changeYear  : true,
});

jQuery('#created_from_date').datepicker({
    dateFormat : 'yy-mm-dd'
});

jQuery('#created_to_date').datepicker({
    dateFormat : 'yy-mm-dd'
});

jQuery('#updated_from_date').datepicker({
    dateFormat : 'yy-mm-dd'
});

jQuery('#updated_to_date').datepicker({
    dateFormat : 'yy-mm-dd'
});
</script>