<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<?php 
echo $this->headTitle(); 
?>
<?php echo $this->headMeta();?>
<meta name="robots" content="nofollow" />
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
<link rel="stylesheet" href="<?php echo $this->baseUrl('skin/front/css/jquery-ui/jquery-ui.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('skin/front/css/bootstrap.css'); ?>" /> 
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('skin/front/css/bootstrap-theme.min.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('skin/front/css/googlefonts.css'); ?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('skin/front/css/theme.css'); ?>" />
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/front/js/jquery.js'); ?>"></script>  
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/front/css/jquery-ui/jquery-ui.min.js'); ?>"></script>  
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/front/js/all.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('skin/front/js/bootstrap.min.js'); ?>"></script>
</head>
